create table "SUS_ROLES" ( "ROLE_ID" number(19,0) not null, "ROLE_NAME" varchar2(255) not null, constraint sus_roles_role_id_pk primary key ( "ROLE_ID" ) );
alter table "SUS_ROLES" add constraint sus_roles_role_name_uk unique ( "ROLE_NAME" );
create sequence "SUS_ROLES_ROLE_ID_SEQ" minvalue 1 start with 1 increment by 1;
create trigger "SUS_ROLES_ROLE_ID_TRG" before insert on "SUS_ROLES" for each row begin if :new."ROLE_ID" is null then select "SUS_ROLES_ROLE_ID_SEQ".nextval into :new."ROLE_ID" from dual; end if; end;
create table "SUS_SCHOOLS" ( "SCHOOL_ID" number(19,0) not null, "SCHOOL_NAME" varchar2(255) not null, constraint sus_schools_school_id_pk primary key ( "SCHOOL_ID" ) );
create sequence "SUS_SCHOOLS_SCHOOL_ID_SEQ" minvalue 1 start with 1 increment by 1;
create trigger "SUS_SCHOOLS_SCHOOL_ID_TRG" before insert on "SUS_SCHOOLS" for each row begin if :new."SCHOOL_ID" is null then select "SUS_SCHOOLS_SCHOOL_ID_SEQ".nextval into :new."SCHOOL_ID" from dual; end if; end;
create table "SUS_USERS" ( "USER_ID" number(19,0) not null, "FULL_NAME" varchar2(255) null, "EMAIL" varchar2(255) not null, "ROLE_ID" number(19,0) not null, "SCHOOL_ID" number(19,0) null, "CREATED_AT" date not null, constraint sus_users_role_id_fk foreign key ( "ROLE_ID" ) references "SUS_ROLES" ( "ROLE_ID" ) on delete cascade, constraint sus_users_school_id_fk foreign key ( "SCHOOL_ID" ) references "SUS_SCHOOLS" ( "SCHOOL_ID" ) on delete set null, constraint sus_users_user_id_pk primary key ( "USER_ID" ) );
alter table "SUS_USERS" add constraint sus_users_email_uk unique ( "EMAIL" );
create sequence "SUS_USERS_USER_ID_SEQ" minvalue 1 start with 1 increment by 1;
create trigger "SUS_USERS_USER_ID_TRG" before insert on "SUS_USERS" for each row begin if :new."USER_ID" is null then select "SUS_USERS_USER_ID_SEQ".nextval into :new."USER_ID" from dual; end if; end;
create table "SUS_EVENTS" ( "EVENT_ID" number(19,0) not null, "SCHOOL_ID" number(19,0) not null, "ENTERED_BY" number(19,0) not null, "EVENT_MONTH" number(10,0) not null, "EVENT_YEAR" number(10,0) not null, "EVENT_NAME" varchar2(255) not null, "EVENT_TYPE" varchar2(255) not null, "EVENT_DATE" date not null, "DESCRIPTION" clob not null, "ATTACHMENT_PATH" varchar2(255) null, "CREATED_AT" date not null, constraint sus_events_school_id_fk foreign key ( "SCHOOL_ID" ) references "SUS_SCHOOLS" ( "SCHOOL_ID" ) on delete cascade, constraint sus_events_entered_by_fk foreign key ( "ENTERED_BY" ) references "SUS_USERS" ( "USER_ID" ) on delete cascade, constraint sus_events_event_id_pk primary key ( "EVENT_ID" ) );
create sequence "SUS_EVENTS_EVENT_ID_SEQ" minvalue 1 start with 1 increment by 1;
create trigger "SUS_EVENTS_EVENT_ID_TRG" before insert on "SUS_EVENTS" for each row begin if :new."EVENT_ID" is null then select "SUS_EVENTS_EVENT_ID_SEQ".nextval into :new."EVENT_ID" from dual; end if; end;
create table "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" number(19,0) not null, "DATA_MONTH" number(10,0) not null, "DATA_YEAR" number(10,0) not null, "CREATED_BY" number(19,0) not null, "CREATED_AT" date not null, constraint su_sustainabil_per_crea_by_fk foreign key ( "CREATED_BY" ) references "SUS_USERS" ( "USER_ID" ) on delete cascade, constraint su_sustainabil_per_per_id_pk primary key ( "PERIOD_ID" ) );
alter table "SUS_SUSTAINABILITY_PERIOD" add constraint su_sustainab_pe_da_mo_da_ye_uk unique ( "DATA_MONTH", "DATA_YEAR" );
create sequence "SUS_SUSTAINABILITY_PERIOD_PERI" minvalue 1 start with 1 increment by 1;
create trigger "SUS_SUSTAINABILITY_PERIOD_PERI" before insert on "SUS_SUSTAINABILITY_PERIOD" for each row begin if :new."PERIOD_ID" is null then select "SUS_SUSTAINABILITY_PERIOD_PERI".nextval into :new."PERIOD_ID" from dual; end if; end;
create table "SUS_PAPER_CONSUMPTION" ( "PAPER_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "PAPER_REAMS" number(10, 2) not null, "SHEETS_PER_REAM" number(10, 2) not null, constraint su_pape_consumptio_perio_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_pape_consumptio_pape_id_pk primary key ( "PAPER_ID" ) );
create sequence "SUS_PAPER_CONSUMPTION_PAPER_ID" minvalue 1 start with 1 increment by 1;
create trigger "SUS_PAPER_CONSUMPTION_PAPER_ID" before insert on "SUS_PAPER_CONSUMPTION" for each row begin if :new."PAPER_ID" is null then select "SUS_PAPER_CONSUMPTION_PAPER_ID".nextval into :new."PAPER_ID" from dual; end if; end;
create table "SUS_ELECTRICITY_CONSUMPTION" ( "ELECTRICITY_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "UNITS_KWH" number(12, 2) not null, "TOTAL_COST" number(15, 2) not null, constraint su_electric_consumpt_per_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_electr_consum_electr_id_pk primary key ( "ELECTRICITY_ID" ) );
create sequence "SUS_ELECTRICITY_CONSUMPTION_EL" minvalue 1 start with 1 increment by 1;
create trigger "SUS_ELECTRICITY_CONSUMPTION_EL" before insert on "SUS_ELECTRICITY_CONSUMPTION" for each row begin if :new."ELECTRICITY_ID" is null then select "SUS_ELECTRICITY_CONSUMPTION_EL".nextval into :new."ELECTRICITY_ID" from dual; end if; end;
create table "SUS_WASTE_GENERATION" ( "WASTE_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "ORGANIC_KG" number(10, 2) not null, "RECYCLABLE_KG" number(10, 2) not null, "OTHER_KG" number(10, 2) not null, constraint su_wast_generatio_perio_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_wast_generatio_wast_id_pk primary key ( "WASTE_ID" ) );
create sequence "SUS_WASTE_GENERATION_WASTE_ID_" minvalue 1 start with 1 increment by 1;
create trigger "SUS_WASTE_GENERATION_WASTE_ID_" before insert on "SUS_WASTE_GENERATION" for each row begin if :new."WASTE_ID" is null then select "SUS_WASTE_GENERATION_WASTE_ID_".nextval into :new."WASTE_ID" from dual; end if; end;
create table "SUS_GENERATOR_USAGE" ( "GENERATOR_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "AVG_RUNNING_HOURS" number(10, 2) not null, "FUEL_LITRES" number(12, 2) not null, constraint su_generato_usag_perio_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_generat_usa_generat_id_pk primary key ( "GENERATOR_ID" ) );
create sequence "SUS_GENERATOR_USAGE_GENERATOR_" minvalue 1 start with 1 increment by 1;
create trigger "SUS_GENERATOR_USAGE_GENERATOR_" before insert on "SUS_GENERATOR_USAGE" for each row begin if :new."GENERATOR_ID" is null then select "SUS_GENERATOR_USAGE_GENERATOR_".nextval into :new."GENERATOR_ID" from dual; end if; end;
create table "SUS_BUSINESS_TRAVEL" ( "TRAVEL_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "TRAVEL_KM" number(12, 2) not null, "FUEL_LITRES" number(12, 2) not null, constraint su_busines_trave_perio_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_busines_trave_trave_id_pk primary key ( "TRAVEL_ID" ) );
create sequence "SUS_BUSINESS_TRAVEL_TRAVEL_ID_" minvalue 1 start with 1 increment by 1;
create trigger "SUS_BUSINESS_TRAVEL_TRAVEL_ID_" before insert on "SUS_BUSINESS_TRAVEL" for each row begin if :new."TRAVEL_ID" is null then select "SUS_BUSINESS_TRAVEL_TRAVEL_ID_".nextval into :new."TRAVEL_ID" from dual; end if; end;
create table "SUS_WATER_CONSUMPTION" ( "WATER_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "UNITS" number(12, 2) not null, "PRICE_PER_UNIT" number(10, 2) not null, constraint su_wate_consumptio_perio_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_wate_consumptio_wate_id_pk primary key ( "WATER_ID" ) );
create sequence "SUS_WATER_CONSUMPTION_WATER_ID" minvalue 1 start with 1 increment by 1;
create trigger "SUS_WATER_CONSUMPTION_WATER_ID" before insert on "SUS_WATER_CONSUMPTION" for each row begin if :new."WATER_ID" is null then select "SUS_WATER_CONSUMPTION_WATER_ID".nextval into :new."WATER_ID" from dual; end if; end;
create table "SUS_CARBON_METRICS" ( "CARBON_ID" number(19,0) not null, "PERIOD_ID" number(19,0) not null, "AQI_SCORE" number(10, 2) not null, "CARBON_FOOTPRINT" number(15, 2) not null, "ENTERED_BY" number(19,0) not null, "CREATED_AT" date not null, constraint su_carbo_metric_perio_id_fk foreign key ( "PERIOD_ID" ) references "SUS_SUSTAINABILITY_PERIOD" ( "PERIOD_ID" ) on delete cascade, constraint su_carbo_metric_entere_by_fk foreign key ( "ENTERED_BY" ) references "SUS_USERS" ( "USER_ID" ) on delete cascade, constraint su_carbo_metric_carbo_id_pk primary key ( "CARBON_ID" ) );
create sequence "SUS_CARBON_METRICS_CARBON_ID_S" minvalue 1 start with 1 increment by 1;
create trigger "SUS_CARBON_METRICS_CARBON_ID_T" before insert on "SUS_CARBON_METRICS" for each row begin if :new."CARBON_ID" is null then select "SUS_CARBON_METRICS_CARBON_ID_S".nextval into :new."CARBON_ID" from dual; end if; end;
select column_name from all_tab_cols where upper(owner) = upper('BNUCMS') and upper(table_name) = upper('SUS_users') order by column_id;
alter table "SUS_USERS" add ( "PASSWORD" varchar2(255) not null );
select column_name from all_tab_cols where upper(owner) = upper('BNUCMS') and upper(table_name) = upper('SUS_sustainability_period') order by column_id;
alter table "SUS_SUSTAINABILITY_PERIOD" add ( "STUDENTS" number(10,0) default '0' not null );
alter table "SUS_SUSTAINABILITY_PERIOD" add ( "EMPLOYEES" number(10,0) default '0' not null );
create table "SUS_PERSONAL_ACCESS_TOKENS" ( "ID" number(19,0) not null, "TOKENABLE_TYPE" varchar2(255) not null, "TOKENABLE_ID" number(19,0) not null, "NAME" clob not null, "TOKEN" varchar2(64) not null, "ABILITIES" clob null, "LAST_USED_AT" timestamp null, "EXPIRES_AT" timestamp null, "CREATED_AT" timestamp null, "UPDATED_AT" timestamp null, constraint su_persona_acces_token_id_pk primary key ( "ID" ) );
create index su_pe_ac_to_tok_ty_tok_id_in on "SUS_PERSONAL_ACCESS_TOKENS" ( "TOKENABLE_TYPE", "TOKENABLE_ID" );
alter table "SUS_PERSONAL_ACCESS_TOKENS" add constraint su_persona_acces_token_toke_uk unique ( "TOKEN" );
create index su_perso_acc_tok_expi_at_in on "SUS_PERSONAL_ACCESS_TOKENS" ( "EXPIRES_AT" );
create sequence "SUS_PERSONAL_ACCESS_TOKENS_ID_" minvalue 1 start with 1 increment by 1;
create trigger "SUS_PERSONAL_ACCESS_TOKENS_ID_" before insert on "SUS_PERSONAL_ACCESS_TOKENS" for each row begin if :new."ID" is null then select "SUS_PERSONAL_ACCESS_TOKENS_ID_".nextval into :new."ID" from dual; end if; end;
SELECT decode(nullable, 'Y', 1, 0) as nullable FROM all_tab_cols WHERE upper(owner) = upper('BNUCMS') AND upper(table_name) = upper('SUS_events') AND upper(column_name) = upper('school_id');
alter table "SUS_EVENTS" modify "SCHOOL_ID" number(19,0) null;
create table "SUS_ANNUAL_METRICS" ( "ID" number(19,0) not null, "YEAR" number(10,0) not null, "SOLAR_OFFSET_KWH" number(15, 2) null, "CREATED_AT" timestamp null, "UPDATED_AT" timestamp null, constraint sus_annual_metrics_id_pk primary key ( "ID" ) );
alter table "SUS_ANNUAL_METRICS" add constraint sus_annual_metrics_year_uk unique ( "YEAR" );
create sequence "SUS_ANNUAL_METRICS_ID_SEQ" minvalue 1 start with 1 increment by 1;
create trigger "SUS_ANNUAL_METRICS_ID_TRG" before insert on "SUS_ANNUAL_METRICS" for each row begin if :new."ID" is null then select "SUS_ANNUAL_METRICS_ID_SEQ".nextval into :new."ID" from dual; end if; end;
alter table "SUS_PAPER_CONSUMPTION" add ( "PER_CAPITA_REAM" number(10, 4) null );
alter table "SUS_ELECTRICITY_CONSUMPTION" add ( "KWH_SOLAR_OFFSET" number(10, 2) null );
alter table "SUS_WASTE_GENERATION" add ( "TOTAL_WASTE" number(10, 2) null );
alter table "SUS_WASTE_GENERATION" add ( "PER_CAPITA_WASTE" number(10, 4) null );
alter table "SUS_GENERATOR_USAGE" add ( "TOTAL_HOURS" number(10, 2) null );
alter table "SUS_GENERATOR_USAGE" add ( "DIESEL_LITRES" number(10, 2) null );
alter table "SUS_GENERATOR_USAGE" add ( "FUEL_TYPE" varchar2(255) null );
alter table "SUS_GENERATOR_USAGE" add ( "COST" number(10, 2) null );
SELECT cols.column_name FROM all_constraints cons, all_cons_columns cols WHERE upper(cols.table_name) = upper('SUS_BUSINESS_TRAVEL') AND upper(cons.owner) = upper('BNUCMS') AND cons.constraint_type = 'P' AND cons.constraint_name = cols.constraint_name AND cons.owner = cols.owner AND cols.position = 1 ORDER BY cols.table_name, cols.position;
SELECT USERNAME FROM all_users WHERE username = 'CTXSYS';
begin execute immediate 'drop table "SUS_BUSINESS_TRAVEL"'; exception when others then null; end;
create table "SUS_SESSIONS" ( "ID" varchar2(255) not null, "USER_ID" number(19,0) null, "IP_ADDRESS" varchar2(45) null, "USER_AGENT" clob null, "PAYLOAD" clob not null, "LAST_ACTIVITY" number(10,0) not null, constraint sus_sessions_id_pk primary key ( "ID" ) );
create index sus_sessions_user_id_index on "SUS_SESSIONS" ( "USER_ID" );
create index su_session_las_activit_inde on "SUS_SESSIONS" ( "LAST_ACTIVITY" );
create table "SUS_CACHE" ( "KEY" varchar2(255) not null, "VALUE" clob not null, "EXPIRATION" number(10,0) not null, constraint sus_cache_key_pk primary key ( "KEY" ) );
create index sus_cache_expiration_index on "SUS_CACHE" ( "EXPIRATION" );
create table "SUS_CACHE_LOCKS" ( "KEY" varchar2(255) not null, "OWNER" varchar2(255) not null, "EXPIRATION" number(10,0) not null, constraint sus_cache_locks_key_pk primary key ( "KEY" ) );
create index su_cach_lock_expiratio_inde on "SUS_CACHE_LOCKS" ( "EXPIRATION" );
create table "SUS_JOBS" ( "ID" number(19,0) not null, "QUEUE" varchar2(255) not null, "PAYLOAD" clob not null, "ATTEMPTS" number(3,0) not null, "RESERVED_AT" number(10,0) null, "AVAILABLE_AT" number(10,0) not null, "CREATED_AT" number(10,0) not null, constraint sus_jobs_id_pk primary key ( "ID" ) );
create index sus_jobs_queue_index on "SUS_JOBS" ( "QUEUE" );
create sequence "SUS_JOBS_ID_SEQ" minvalue 1 start with 1 increment by 1;
create trigger "SUS_JOBS_ID_TRG" before insert on "SUS_JOBS" for each row begin if :new."ID" is null then select "SUS_JOBS_ID_SEQ".nextval into :new."ID" from dual; end if; end;