<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $table) {
            // Oracle identity column (NUMBER generated by default as identity)
            // In older Oracle versions it might be separate sequence/trigger, 
            // but Laravel's id() or identity() usually handles auto-increment logic.
            // Requirement said: "Use $table->id() only if compatible with Oracle identity columns".
            // Typically $table->id() creates a BigInteger (NUMBER(20)) PK with auto increment.
            // To strictly follow "Avoid unsignedBigInteger()" if it means literally the method call, 
            // we can use standard integer/bigInteger, but id() is standard Laravel for PK.
            // Ensuring we use Oracle compatible types.
            
            $table->id('role_id'); 
            $table->string('role_name')->unique();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('roles');
    }
};
